# -*- coding: utf-8 -*-
"""show_gemmimol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7b45FIxjhk62TD4kNBGAPbevGV7q96C
"""

"""
    1. `V.load_model(...)` — GemmiMol automatically positions the camera
   (MANUAL recenter is NOT called — this provides the correct,
    close, readable view similar to the website version)

    2. Sequential sources for MTZ:
     a) PDBe:     https://www.ebi.ac.uk/pdbe/coordinates/files/<id>_map.mtz
     b) PDB-REDO: https://pdb-redo.eu/db/<id>/<id>_final.mtz

    3. For the model in PDB:
     PDBe `_updated.cif` is preferred because it is a Gemmi-friendly format
     and does not require normalization.

    4. 2Fo-Fc map calculated from the model for COD/CCD.

"""

from IPython.display import HTML, display
import uuid
import json
import base64
import os
import tempfile

try:
    import requests
    _HAS_REQUESTS = True
except ImportError:
    _HAS_REQUESTS = False
    import urllib.request


# URL helpers
def _pdbe_updated_cif_url(pdb_id: str) -> str:
    """PDBe `_updated.cif` — Gemmi-friendly format."""
    return (f"https://www.ebi.ac.uk/pdbe/entry-files/download/"
            f"{pdb_id.lower()}_updated.cif")


def _rcsb_cif_url(pdb_id: str) -> str:
    """RCSB mmCIF — fallback if PDBe is unavailable."""
    return f"https://files.rcsb.org/download/{pdb_id.upper()}.cif"


def _pdbe_mtz_url(pdb_id: str) -> str:
    return f"https://www.ebi.ac.uk/pdbe/coordinates/files/{pdb_id.lower()}_map.mtz"


def _pdb_redo_mtz_url(pdb_id: str) -> str:
    pid = pdb_id.lower()
    return f"https://pdb-redo.eu/db/{pid}/{pid}_final.mtz"


def _cod_url(cod_id: str) -> str:
    return f"https://www.crystallography.net/cod/{cod_id.strip()}.cif"


def _ccd_url(ccd_id: str) -> str:
    ccd = ccd_id.strip().upper()
    return (
        f"https://raw.githubusercontent.com/MonomerLibrary/monomers/"
        f"master/{ccd[0].lower()}/{ccd}.cif"
    )


def _http_get_text(url: str, timeout: int = 30, retries: int = 3) -> str:
    """
    HTTP GET (text). Resistant to errors:
  - Cache: the same URL is not downloaded a second time.
  - Retries: retries up to 3 times for ConnectionReset, timeout,
    and 5xx errors (1s, 2s, 4s exponential backoff).
  - HTTPS → HTTP fallback: some academic servers may fail with TLS errors.
    """
    cached = _CACHE.get(url)
    if cached is not None:
        return cached

    text = _http_get_text_with_retries(url, timeout=timeout, retries=retries)
    _CACHE[url] = text
    return text


def _http_get_text_with_retries(url: str, timeout: int, retries: int) -> str:
    import time
    candidates = [url]
    # If HTTPS fails, also try HTTP
    if url.startswith("https://"):
        candidates.append("http://" + url[len("https://"):])

    last_err = None
    for candidate in candidates:
        for attempt in range(retries):
            try:
                if _HAS_REQUESTS:
                    r = requests.get(
                        candidate, timeout=timeout,
                        headers={"User-Agent": "gemmimol-notebook/1.0"},
                    )
                    r.raise_for_status()
                    return r.text
                else:
                    req = urllib.request.Request(
                        candidate,
                        headers={"User-Agent": "gemmimol-notebook/1.0"},
                    )
                    with urllib.request.urlopen(req, timeout=timeout) as resp:
                        return resp.read().decode("utf-8", errors="replace")
            except Exception as e:
                last_err = e
                # 4xx (404, 403, etc.) — no need to retry
                if _HAS_REQUESTS and isinstance(
                    e, requests.exceptions.HTTPError
                ):
                    status = getattr(e.response, "status_code", 0)
                    if 400 <= status < 500:
                        break  # stop for this candidate, move on to the next one
                # Backoff: 1s, 2s, 4s ...
                if attempt < retries - 1:
                    time.sleep(2 ** attempt)
    raise RuntimeError(
        f"URL could not be downloaded (after retries): {url}\n"
        f"Last Error: {last_err}\n"
        f"Fallback: you can download the file via browser and load it using `model_text=`."
    )


def _http_head_ok(url: str, timeout: int = 10) -> bool:
    cache_key = ("HEAD", url)
    cached = _CACHE.get(cache_key)
    if cached is not None:
        return cached
    try:
        if _HAS_REQUESTS:
            r = requests.head(
                url, timeout=timeout, allow_redirects=True,
                headers={"User-Agent": "gemmimol-notebook/1.0"},
            )
            ok = r.status_code < 400
        else:
            req = urllib.request.Request(
                url, method="HEAD",
                headers={"User-Agent": "gemmimol-notebook/1.0"},
            )
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                ok = 200 <= resp.status < 400
    except Exception:
        ok = False
    _CACHE[cache_key] = ok
    return ok


def clear_cache():
    """Clears the cache of files downloaded by `show_gemmimol`."""
    _CACHE.clear()
    print("Cache cleared")

# Module-level cache
_CACHE: dict = {}



# CIF NORMALIZATION (Gemmi WASM-compatible)

def _normalize_cif(cif_text: str, kind_hint: str = "auto"):
    """
    Returns: (normalized_text, detected_kind, extracted_pdb_id_or_None)
    """
    try:
        import gemmi
    except ImportError:
        return cif_text, "raw", None

    tmp = None
    try:
        suffix = ".cif"
        if cif_text.lstrip().startswith(("HEADER", "ATOM ", "HETATM", "TITLE",
                                          "REMARK", "CRYST1")):
            suffix = ".pdb"

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=suffix, delete=False, encoding="utf-8"
        ) as f:
            f.write(cif_text)
            tmp = f.name

        # 1) MACROMOLECULE ATTEMPT
        if kind_hint in ("auto", "macro"):
            try:
                st = gemmi.read_structure(tmp, merge_chain_parts=True)
                if st and len(st) > 0:
                    extracted_pdb = _extract_pdb_id(cif_text, suffix)
                    try:
                        st.setup_entities()
                    except Exception:
                        pass
                    with tempfile.NamedTemporaryFile(
                        mode="w", suffix=".cif", delete=False, encoding="utf-8"
                    ) as g:
                        out_path = g.name
                    try:
                        if hasattr(st, "make_mmcif_document"):
                            doc = st.make_mmcif_document()
                            doc.write_file(out_path)
                        else:
                            st.write_mmcif(out_path)
                        with open(out_path, "r", encoding="utf-8") as g:
                            normalized = g.read()
                        if normalized.strip():
                            return normalized, "macro", extracted_pdb
                    finally:
                        if os.path.exists(out_path):
                            try: os.unlink(out_path)
                            except OSError: pass
            except Exception:
                pass

        # 2) SMALL MOLECULE (COD) ATTEMPT
        if kind_hint in ("auto", "small"):
            try:
                small = None
                if hasattr(gemmi, "read_small_structure"):
                    small = gemmi.read_small_structure(tmp)
                elif hasattr(gemmi, "make_small_structure_from_block"):
                    doc = gemmi.cif.read(tmp)
                    if len(doc) > 0:
                        small = gemmi.make_small_structure_from_block(doc[0])
                if small and len(small.sites) > 0:
                    return _small_structure_to_mmcif(small), "small", None
            except Exception:
                pass

        # 3) MONOMER (CCD) ATTEMPT
        if kind_hint in ("auto", "monomer"):
            try:
                doc = gemmi.cif.read(tmp)
                if len(doc) > 0:
                    block = doc[0]
                    out = _monomer_to_mmcif(block)
                    if out:
                        return out, "monomer", None
            except Exception:
                pass

        return cif_text, "raw", None

    finally:
        if tmp and os.path.exists(tmp):
            try: os.unlink(tmp)
            except OSError: pass


def _quick_extract_pdb_id(cif_text: str):
    """
    Quick (non-parsing) search for `_entry.id` in the text.
    Only text search; does not use Gemmi — the purpose of this function
    is to decide whether "this file is a PDB", so dangerous normalization
    can be skipped.
    """
    #Search directly for `data_XXXX` in the text
    for line in cif_text.splitlines()[:50]:  #first 50 lines are sufficient
        line = line.strip()
        if line.startswith("data_"):
            name = line[5:].strip()
            if len(name) == 4 and name.isalnum():
                return name.upper()
        elif line.startswith("_entry.id"):
            parts = line.split(None, 1)
            if len(parts) == 2:
                val = parts[1].strip().strip("'").strip('"')
                if len(val) == 4 and val.isalnum():
                    return val.upper()
    return None


def _extract_pdb_id(cif_text: str, suffix: str):
    """Extract the 4-character PDB ID from mmCIF/PDB."""
    try:
        import gemmi
    except ImportError:
        return None

    # PDB format
    if suffix == ".pdb":
        for line in cif_text.splitlines():
            if line.startswith("HEADER") and len(line) >= 66:
                c = line[62:66].strip()
                if len(c) == 4 and c.isalnum():
                    return c.upper()
        return None

    # mmCIF format
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".cif", delete=False, encoding="utf-8"
        ) as f:
            f.write(cif_text)
            p = f.name
        try:
            doc = gemmi.cif.read(p)
            if len(doc) == 0:
                return None
            block = doc[0]
            try:
                val = block.find_value("_entry.id")
                if val:
                    val = val.strip().strip("'").strip('"')
                    if len(val) == 4 and val.isalnum():
                        return val.upper()
            except Exception:
                pass
            name = (block.name or "").strip()
            if len(name) == 4 and name.isalnum():
                return name.upper()
        finally:
            if os.path.exists(p):
                try: os.unlink(p)
                except OSError: pass
    except Exception:
        pass
    return None


def _small_structure_to_mmcif(small) -> str:
    """Gemmi SmallStructure → minimal mmCIF."""
    cell = small.cell
    sg = small.spacegroup_hm or "P 1"
    lines = [
        f"data_{(small.name or 'small').replace(' ', '_')}",
        f"_cell.length_a       {cell.a:.4f}",
        f"_cell.length_b       {cell.b:.4f}",
        f"_cell.length_c       {cell.c:.4f}",
        f"_cell.angle_alpha    {cell.alpha:.3f}",
        f"_cell.angle_beta     {cell.beta:.3f}",
        f"_cell.angle_gamma    {cell.gamma:.3f}",
        f"_symmetry.space_group_name_H-M  '{sg}'",
        "#",
        "loop_",
        "_atom_site.group_PDB", "_atom_site.id", "_atom_site.type_symbol",
        "_atom_site.label_atom_id", "_atom_site.label_alt_id",
        "_atom_site.label_comp_id", "_atom_site.label_asym_id",
        "_atom_site.label_entity_id", "_atom_site.label_seq_id",
        "_atom_site.Cartn_x", "_atom_site.Cartn_y", "_atom_site.Cartn_z",
        "_atom_site.occupancy", "_atom_site.B_iso_or_equiv",
        "_atom_site.auth_asym_id", "_atom_site.auth_seq_id",
    ]
    for i, site in enumerate(small.sites, start=1):
        try:
            pos = site.orth(cell)
            x, y, z = pos.x, pos.y, pos.z
        except Exception:
            try:
                pos = cell.orthogonalize(site.fract)
                x, y, z = pos.x, pos.y, pos.z
            except Exception:
                x = y = z = 0.0
        elem = (site.type_symbol or "C").strip()
        label = site.label or f"{elem}{i}"
        safe = "".join(c for c in label if c.isalnum() or c == "_")[:20] or f"A{i}"
        lines.append(
            f"HETATM {i} {elem} {safe} . LIG A 1 1 "
            f"{x:.4f} {y:.4f} {z:.4f} 1.00 20.00 A 1"
        )
    return "\n".join(lines) + "\n"


def _monomer_to_mmcif(block):
    """CCD monomer (chem_comp_atom) → minimal mmCIF."""
    try:
        import gemmi
    except ImportError:
        return None
    rows = []
    for col_set in (
        ["atom_id", "type_symbol",
         "model_Cartn_x", "model_Cartn_y", "model_Cartn_z"],
        ["atom_id", "type_symbol",
         "pdbx_model_Cartn_x_ideal",
         "pdbx_model_Cartn_y_ideal",
         "pdbx_model_Cartn_z_ideal"]
    ):
        try:
            table = block.find("_chem_comp_atom.", col_set)
            for r in table:
                try:
                    rows.append((r[0], r[1], float(r[2]), float(r[3]), float(r[4])))
                except (ValueError, IndexError):
                    continue
            if rows:
                break
        except Exception:
            continue
    if not rows:
        return None
    comp_id = (block.name.replace("comp_", "") or "LIG")[:3].upper()
    lines = [
        f"data_{comp_id}",
        "_cell.length_a 1.0", "_cell.length_b 1.0", "_cell.length_c 1.0",
        "_cell.angle_alpha 90.0", "_cell.angle_beta 90.0", "_cell.angle_gamma 90.0",
        "_symmetry.space_group_name_H-M  'P 1'",
        "#", "loop_",
        "_atom_site.group_PDB", "_atom_site.id", "_atom_site.type_symbol",
        "_atom_site.label_atom_id", "_atom_site.label_alt_id",
        "_atom_site.label_comp_id", "_atom_site.label_asym_id",
        "_atom_site.label_entity_id", "_atom_site.label_seq_id",
        "_atom_site.Cartn_x", "_atom_site.Cartn_y", "_atom_site.Cartn_z",
        "_atom_site.occupancy", "_atom_site.B_iso_or_equiv",
        "_atom_site.auth_asym_id", "_atom_site.auth_seq_id",
    ]
    for i, (atom_id, sym, x, y, z) in enumerate(rows, start=1):
        safe = "".join(c for c in atom_id if c.isalnum() or c in "_'\"")[:20] \
               or f"A{i}"
        sym = sym.strip() or "C"
        lines.append(
            f"HETATM {i} {sym} {safe} . {comp_id} A 1 1 "
            f"{x:.4f} {y:.4f} {z:.4f} 1.00 20.00 A 1"
        )
    return "\n".join(lines) + "\n"


# Calculate CCP4 from the model (for small molecules)

def _compute_ccp4_from_structure(cif_text: str, d_min: float = 2.0):
    try:
        import gemmi
    except ImportError:
        return None
    cif_tmp = ccp4_tmp = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".cif", delete=False, encoding="utf-8"
        ) as f:
            f.write(cif_text)
            cif_tmp = f.name
        st = gemmi.read_structure(cif_tmp)
        if not st or not st[0]:
            return None
        dencalc = gemmi.DensityCalculatorX()
        dencalc.d_min = d_min
        dencalc.rate = 1.5
        try:
            dencalc.set_refmac_compatible_blur(st[0])
        except Exception:
            pass
        dencalc.grid.setup_from(st)
        dencalc.put_model_density_on_grid(st[0])
        ccp4 = gemmi.Ccp4Map()
        ccp4.grid = dencalc.grid
        ccp4.update_ccp4_header()
        with tempfile.NamedTemporaryFile(suffix=".ccp4", delete=False) as f:
            ccp4_tmp = f.name
        ccp4.write_ccp4_map(ccp4_tmp)
        with open(ccp4_tmp, "rb") as f:
            return f.read()
    except Exception:
        return None
    finally:
        for p in (cif_tmp, ccp4_tmp):
            if p and os.path.exists(p):
                try: os.unlink(p)
                except OSError: pass


# Main function
def show_gemmimol(
    # model
    model_url=None,
    model_text=None,
    pdb_id=None,
    cod_id=None,
    ccd_id=None,
    code=None,
    # density
    mtz_url=None,
    mtz_columns=None,
    map_url=None,
    diff_map_url=None,
    map_bytes=None,
    auto_density=True,
    fallback_compute=False,
    auto_compute_for_small=True,
    d_min=2.0,
    # view
    width="100%",
    height="720px",
    background="#000000",
    ligand_style="ball&stick",
    ball_size=0.24,
    hydrogens=False,
    verbose=True,
):
    """
    GemmiMol notebook viewer.

    Examples :
    show_gemmimol(pdb_id="4UN4")
    show_gemmimol(code="9R1V")    # PDBe fails → PDB-REDO fallback
    show_gemmimol(code="ATP")
    show_gemmimol(code="1542540")
    show_gemmimol(model_text=open("9R1V.cif").read())
    """
    # 1) Get the model text
    model_label, raw_text, resolved_pdb, source_kind = _resolve_model(
        model_url=model_url, model_text=model_text,
        pdb_id=pdb_id, cod_id=cod_id, ccd_id=ccd_id, code=code,
        verbose=verbose,
    )

    # 2) Normalization strategy
    # IMPORTANT: PDB mmCIF files (PDBe `_updated.cif` / RCSB) can be read directly
    # by Gemmi WASM. Roundtrip normalization may remove important fields
    # (REFMAC fields, cell-MTZ relationships) and can cause spatial
    # inconsistency between density and model.
    # Therefore strategy:
    #   • If PDB ID is known + pure PDB source → keep original
    #   • If model_text contains _entry.id → keep original, extract PDB ID
    #   • COD / CCD / monomer / non-standard → normalization is required

    extracted_pdb = None
    detected_kind = source_kind

    if source_kind == "macro" and resolved_pdb:
        # Downloaded directly from PDBe/RCSB — no modifications applied
        normalized = raw_text
        extracted_pdb = resolved_pdb
        if verbose:
            _log("PDB file is kept in its original form (for density compatibility)")
    else:
        # Maybe the model_text contains a hidden PDB file — first try to extract the PDB ID
        if source_kind == "auto" and model_text is not None:
            quick_pdb = _quick_extract_pdb_id(raw_text)
            if quick_pdb:
                # PDB file — no normalization needed
                normalized = raw_text
                detected_kind = "macro"
                extracted_pdb = quick_pdb
                if verbose:
                    _log(f"PDB ID '{quick_pdb}' found in mmCIF — file is kept in its original form")
            else:
                # Full normalization
                normalized, detected_kind, extracted_pdb = _normalize_cif(
                    raw_text, kind_hint=source_kind
                )
        else:
            # COD / CCD / monomer — normalization is required
            normalized, detected_kind, extracted_pdb = _normalize_cif(
                raw_text, kind_hint=source_kind
            )

    if not resolved_pdb and extracted_pdb:
        resolved_pdb = extracted_pdb
        if verbose:
            _log(f"PDBe MTZ search enabled for '{extracted_pdb}'.")

    if verbose:
        _log(f"Model ready: {len(normalized):,} symbol(s) ({detected_kind})")

    map_info = _resolve_density(
        cif_text=normalized,
        resolved_pdb=resolved_pdb,
        mtz_url=mtz_url, mtz_columns=mtz_columns,
        map_url=map_url, diff_map_url=diff_map_url,
        map_bytes=map_bytes,
        auto_density=auto_density,
        fallback_compute=fallback_compute,
        auto_compute_for_small=auto_compute_for_small,
        d_min=d_min,
        source_kind=detected_kind,
        verbose=verbose,
    )

    ns = uuid.uuid4().hex[:10]
    html = _build_html(
        ns=ns, cif_text=normalized, model_label=model_label,
        map_info=map_info, detected_kind=detected_kind,
        width=width, height=height, background=background,
        ligand_style=ligand_style, ball_size=ball_size, hydrogens=hydrogens,
    )
    display(HTML(html))


# Helpers
def _log(msg: str):
    print(msg)


def _resolve_model(model_url, model_text, pdb_id, cod_id, ccd_id, code,
                   verbose=True):
    """
    Returns: (label, text, resolved_pdb_or_None, source_kind_hint)
    For PDB: PDBe `_updated.cif` is preferred, RCSB is fallback.
    """
    if code is not None and not (pdb_id or cod_id or ccd_id
                                 or model_url or model_text):
        c = code.strip()
        upper = c.upper()
        if upper.startswith("PDB:"):
            pdb_id = upper.split(":", 1)[1]
        elif upper.startswith("COD:"):
            cod_id = upper.split(":", 1)[1]
        elif upper.startswith(("CCD:", "LIG:")):
            ccd_id = upper.split(":", 1)[1]
        elif c.isdigit():
            cod_id = c
        elif len(c) == 4 and c.isalnum():
            pdb_id = upper
        elif 1 <= len(c) <= 3 and c.isalnum():
            ccd_id = upper
        else:
            raise ValueError(f"Kod '{code}' tanınmadı.")

    if model_text is not None:
        return ("LOCAL", model_text, None, "auto")

    if model_url is not None:
        text = _http_get_text(model_url)
        label = os.path.splitext(os.path.basename(model_url))[0].upper() or "MODEL"
        return (label, text, None, "auto")

    if pdb_id is not None:
        pdb_id = pdb_id.strip().upper()
        # Try PDBe _updated.cif first (Gemmi-friendly)
        try:
            url = _pdbe_updated_cif_url(pdb_id)
            if verbose:
                _log(f"Downloading from PDBe: {url}")
            text = _http_get_text(url)
            return (f"PDB {pdb_id}", text, pdb_id, "macro")
        except Exception as e:
            if verbose:
                _log(f"PDBe download failed ({e}), trying RCSB...")
            text = _http_get_text(_rcsb_cif_url(pdb_id))
            return (f"PDB {pdb_id}", text, pdb_id, "macro")

    if cod_id is not None:
        cod_id = cod_id.strip()
        text = _http_get_text(_cod_url(cod_id))
        return (f"COD {cod_id}", text, None, "small")

    if ccd_id is not None:
        ccd_id = ccd_id.strip().upper()
        text = _http_get_text(_ccd_url(ccd_id))
        return (f"CCD {ccd_id}", text, None, "monomer")

    raise ValueError("No model source provided.")


def _resolve_density(cif_text, resolved_pdb,
                     mtz_url, mtz_columns, map_url, diff_map_url, map_bytes,
                     auto_density, fallback_compute,
                     auto_compute_for_small,
                     d_min, source_kind, verbose):
    """

    Density loading strategy :
    1) Directly provided URL/bytes
    2) Small molecule → computed map
    3) PDB macromolecule → PDBe MTZ → fallback PDB-REDO MTZ
    4) Last resort → compute from model (slow)
    """
    info = {
        "kind": None, "mtz_url": None, "mtz_columns": None,
        "map_url": None, "diff_map_url": None, "map_b64": None,
        "label": "",
    }

    # 1) Explicitly provided sources
    if map_bytes is not None:
        info["kind"] = "ccp4-bytes"
        info["map_b64"] = base64.b64encode(map_bytes).decode("ascii")
        info["label"] = "local CCP4 map"
        return info

    if mtz_url:
        info["kind"] = "mtz"
        info["mtz_url"] = mtz_url
        info["mtz_columns"] = list(mtz_columns) if mtz_columns else None
        info["label"] = f"MTZ ({mtz_url.split('/')[-1]})"
        return info

    if map_url or diff_map_url:
        info["kind"] = "ccp4"
        info["map_url"] = map_url
        info["diff_map_url"] = diff_map_url
        info["label"] = "CCP4 map URL"
        return info

    # 2) Small molecule → compute from model
    if source_kind in ("small", "monomer"):
        if auto_compute_for_small:
            if verbose:
                _log(f"Density is calculated for the small molecule (d_min={d_min} Å)...")
            ccp4 = _compute_ccp4_from_structure(cif_text, d_min=d_min)
            if ccp4:
                info["kind"] = "ccp4-bytes"
                info["map_b64"] = base64.b64encode(ccp4).decode("ascii")
                info["label"] = f"calculated 2Fo-Fc map (d_min={d_min} Å)"
                if verbose:
                    _log(f"{len(ccp4):,} CCP4 bytes created")
                return info
        return info

    # 3) Macromolecule → PDBe → PDB-REDO sequence
    if auto_density and resolved_pdb:
        pdbe = _pdbe_mtz_url(resolved_pdb)
        if verbose:
            _log(f"Searching PDBe MTZ: {pdbe}")
        if _http_head_ok(pdbe):
            info["kind"] = "mtz"
            info["mtz_url"] = pdbe
            info["label"] = f"PDBe MTZ ({resolved_pdb})"
            if verbose:
                _log("PDBe MTZ found")
            return info

        # PDB-REDO fallback (important for newer structures)
        redo = _pdb_redo_mtz_url(resolved_pdb)
        if verbose:
            _log(f"Not found in PDBe. Searching PDB-REDO: {redo}")
        if _http_head_ok(redo):
            info["kind"] = "mtz"
            info["mtz_url"] = redo
            info["label"] = f"PDB-REDO MTZ ({resolved_pdb})"
            if verbose:
                _log("PDB-REDO MTZ found")
            return info

        if verbose:
            _log("Neither PDBe nor PDB-REDO MTZ was found")

    # 4) Last resort
    if fallback_compute:
        if verbose:
            _log(f"Density is calculated from the model (d_min={d_min} Å)...")
        ccp4 = _compute_ccp4_from_structure(cif_text, d_min=d_min)
        if ccp4:
            info["kind"] = "ccp4-bytes"
            info["map_b64"] = base64.b64encode(ccp4).decode("ascii")
            info["label"] = f"calculated map (d_min={d_min} Å)"
            return info

    return info

# HTML builder
def _build_html(ns, cif_text, model_label, map_info, detected_kind,
                width, height, background,
                ligand_style, ball_size, hydrogens):
    viewer_id = f"viewer_{ns}"
    hud_id = f"hud_{ns}"
    help_id = f"help_{ns}"
    inset_id = f"inset_{ns}"
    overlay_id = f"overlay_{ns}"
    wrap_class = f"gm-wrap-{ns}"
    badge_id = f"badge_{ns}"

    model_blob_js = (
        f"const __modelText = {json.dumps(cif_text)};\n"
        f"const __blob = new Blob([__modelText], {{type: 'text/plain'}});\n"
        f"const __modelSrc = URL.createObjectURL(__blob);"
    )

    map_js = _build_map_js(map_info, viewer_var="V")

    map_status = ""
    if map_info["kind"]:
        map_status = f"{map_info['label']}"
    elif detected_kind in ("small", "monomer"):
        map_status = "density is not available"

    # Automatically open cell box for small molecules
    is_small = detected_kind in ("small", "monomer")

    viewer_opts = {
        "viewer": viewer_id,
        "hud": hud_id,
        "help": help_id,
        "inset": inset_id,
        "hydrogens": bool(hydrogens),
        "ligand_style": ligand_style,
        "ball_size": float(ball_size),
    }

    html = f"""
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/gemmimol/gemmimol@main/gemmimol.css">

<style>
  .{wrap_class} {{
    position: relative;
    width: {width};
    height: {height};
    background: {background};
    border: 1px solid #222;
    border-radius: 6px;
    overflow: visible;
    font-family: 'Segoe UI', system-ui, sans-serif;
  }}
  .{wrap_class} #{viewer_id} {{
    position: absolute; inset: 0;
    width: 100%; height: 100%;
    border-radius: 6px;
    overflow: hidden;
  }}
  .{wrap_class} #{overlay_id} {{
    position: absolute;
    top: 0; left: 0; right: 0;
    z-index: 30;
  }}
  .{wrap_class} #{inset_id} {{
    position: absolute;
    right: 8px; bottom: 8px;
    width: 96px; height: 96px;
    z-index: 20;
    pointer-events: none;
  }}
  .{wrap_class} #{badge_id} {{
    position: absolute;
    top: 6px;
    right: 12px;
    z-index: 5;
    color: #aaa;
    font-size: 13px;
    font-weight: bold;
    letter-spacing: 1px;
    text-shadow: 0 1px 2px #000;
    pointer-events: none;
  }}
  .{wrap_class} #{badge_id} .gm-sub {{
    display: block;
    font-size: 10px;
    color: #5dd8f0;
    font-weight: normal;
    margin-top: 2px;
  }}
  .gm-status-{ns} {{
    font-family: 'Segoe UI', system-ui, sans-serif;
    font-size: 12px;
    color: #555;
    margin: 4px 0 6px 0;
  }}
</style>

<div class="gm-status-{ns}" id="status_{ns}">
  Loading: <b>{model_label}</b>
  {('· ' + map_status) if map_status else ''}
</div>

<div class="{wrap_class}">
  <div id="{viewer_id}"></div>
  <div id="{overlay_id}">
    <header id="{hud_id}"
            onmousedown="event.stopPropagation();"
            ondblclick="event.stopPropagation();"></header>
  </div>
  <footer id="{help_id}"></footer>
  <div id="{inset_id}"></div>
  <div id="{badge_id}">
    {model_label}
    {('<span class="gm-sub">' + map_status + '</span>') if map_status else ''}
  </div>
</div>

<script src="https://cdn.jsdelivr.net/gh/gemmimol/gemmimol@main/gemmimol.js"></script>
<script src="https://cdn.jsdelivr.net/gh/gemmimol/gemmimol@main/vendor/wasm/gemmi.js"></script>

<script>
(function() {{
  const statusEl = document.getElementById("status_{ns}");
  function setStatus(t) {{ if (statusEl) statusEl.innerHTML = t; }}

  try {{
    if (typeof GM === "undefined")
      throw new Error("GemmiMol script failed to load.");
    if (typeof Gemmi === "undefined")
      throw new Error("Gemmi WASM module failed to load.");

    {model_blob_js}


    const V = new GM.Viewer({json.dumps(viewer_opts)});
    window["gm_{ns}"] = V;
    V.hud("loading {model_label}...");

    Gemmi().then(function(gemmi) {{
      V.load_model(__modelSrc, {{gemmi: gemmi}}, function() {{

      // IMPORTANT: There is NO manual recenter().
      // GemmiMol automatically finds the model center and
      // positions the camera at an optimal distance. This produces
      // the same close, readable view as the official demos.

      // Show cell box only for small molecules
        if ({json.dumps(is_small)}) {{
          try {{ V.toggle_cell_box(); }} catch(_) {{}}
        }}

        // Density Map (if available)
        {map_js}

        setStatus("Ready: <b>{model_label}</b>"
                  + ({json.dumps(map_status)} ? " · " + {json.dumps(map_status)} : ""));
      }});
    }}).catch(function(err) {{
      console.error(err);
      setStatus('<span style="color:#c33">Gemmi WASM error: '
                + err.message + '</span>');
    }});

  }} catch (err) {{
    console.error("GemmiMol error:", err);
    setStatus('<span style="color:#c33">Error: ' + err.message + '</span>');
  }}
}})();
</script>
"""
    return html


def _build_map_js(map_info, viewer_var: str) -> str:
    kind = map_info["kind"]
    if not kind:
        return "// no density map"

    if kind == "mtz":
        cols = (json.dumps(map_info["mtz_columns"])
                if map_info["mtz_columns"] else "undefined")
        url = json.dumps(map_info["mtz_url"])
        return f"""
        try {{
          {viewer_var}.hud("loading map (MTZ)...");
          if (typeof GM.load_maps_from_mtz === "function") {{
            GM.load_maps_from_mtz(gemmi, {viewer_var}, {url}, {cols});
          }}
        }} catch (e) {{ console.error("MTZ error:", e); }}
        """

    if kind == "ccp4":
        parts = []
        if map_info["map_url"]:
            parts.append(
                f"try {{ {viewer_var}.load_map({json.dumps(map_info['map_url'])}, false); }}"
                f" catch(e) {{ console.error(e); }}"
            )
        if map_info["diff_map_url"]:
            parts.append(
                f"try {{ {viewer_var}.load_map({json.dumps(map_info['diff_map_url'])}, true); }}"
                f" catch(e) {{ console.error(e); }}"
            )
        return f"""
        {viewer_var}.hud("loading map (CCP4)...");
        {"; ".join(parts)}
        """

    if kind == "ccp4-bytes":
        b64 = map_info["map_b64"]
        return f"""
        try {{
          {viewer_var}.hud("loading map (computed)...");
          const __b64 = {json.dumps(b64)};
          const __bin = atob(__b64);
          const __u8 = new Uint8Array(__bin.length);
          for (let i = 0; i < __bin.length; i++) __u8[i] = __bin.charCodeAt(i);
          const __blob2 = new Blob([__u8], {{type:'application/octet-stream'}});
          const __mapUrl = URL.createObjectURL(__blob2);
          {viewer_var}.load_map(__mapUrl, false);
        }} catch (e) {{ console.error(e); }}
        """
    return "// unknown"


# Demo
if __name__ == "__main__":
    print("The show_gemmimol module was loaded successfully.")
    print("Usage: in a notebook, run `from show_gemmimol import show_gemmimol`")
    print("Then:    show_gemmimol(pdb_id='4UN4')")